export interface School {
  id: string;
  name: string;
  departments: string[];
}

export const SCHOOLS: School[] = [
  {
    id: "ui",
    name: "University of Ibadan",
    departments: [
      "Agricultural Extension and Rural Development",
      "Agricultural Economics",
      "Agronomy",
      "Animal Science",
      "Aquaculture and Fisheries Management",
      "Botany",
      "Biochemistry",
      "Chemistry",
      "Computer Science",
      "Crop Protection and Environmental Biology",
      "Economics",
      "English",
      "Geography",
      "Geology",
      "History",
      "Industrial Chemistry",
      "Industrial and Production Engineering",
      "Linguistics",
      "Mathematics",
      "Microbiology",
      "Physics",
      "Political Science",
      "Psychology",
      "Sociology",
      "Statistics",
      "Veterinary Anatomy",
      "Veterinary Medicine",
      "Zoology",
      "Theatre Arts",
      "Fine Art",
      "Pharmacy",
      "Nursing Science",
      "Dentistry",
    ],
  },
  {
    id: "unilag",
    name: "University of Lagos",
    departments: [
      "Accounting",
      "Actuarial Science",
      "Architecture",
      "Banking and Finance",
      "Building",
      "Chemical and Petroleum Engineering",
      "Civil and Environmental Engineering",
      "Computer Engineering",
      "Computer Science",
      "Economics",
      "Electrical and Electronics Engineering",
      "English",
      "Estate Management",
      "Geology/Geosciences",
      "History and Strategic Studies",
      "Law",
      "Linguistics, African and Asian Studies",
      "Marine Biology",
      "Mathematics",
      "Mechanical Engineering",
      "Metallurgical and Materials Engineering",
      "Microbiology",
      "Nursing",
      "Pharmacy",
      "Physics",
      "Political Science",
      "Psychology",
      "Radiography",
      "Social Work",
      "Sociology",
      "Surveying and Geoinformatics",
      "Systems Engineering",
      "Urban and Regional Planning",
      "Mass Communication",
      "Fine and Applied Arts",
    ],
  },
  {
    id: "covenant",
    name: "Covenant University",
    departments: [
      "Accounting",
      "Architecture",
      "Banking and Finance",
      "Biochemistry",
      "Biological Sciences",
      "Building Technology",
      "Business Management",
      "Chemical Engineering",
      "Chemistry",
      "Civil Engineering",
      "Computer and Information Sciences",
      "Economics and Development Studies",
      "Electrical and Information Engineering",
      "Mechanical Engineering",
      "Petroleum Engineering",
      "Software Engineering",
      "Estate Management",
      "Mathematics",
      "Physics",
      "Mass Communication",
    ],
  },
  {
    id: "oau",
    name: "Obafemi Awolowo University",
    departments: [
      "Accounting",
      "Adult Education",
      "Agricultural Economics",
      "Animal Science",
      "Architecture",
      "Biochemistry",
      "Botany",
      "Chemical Engineering",
      "Civil Engineering",
      "Computer Science",
      "Dentistry",
      "Drama",
      "Economics",
      "English Language",
      "Fine Arts",
      "French",
      "Geography",
      "History",
      "Industrial Design",
      "Law",
      "Linguistics",
      "Mathematics",
      "Mechanical Engineering",
      "Medicine and Surgery",
      "Microbiology",
      "Music",
      "Pharmacy",
      "Physics",
      "Political Science",
      "Psychology",
      "Sociology",
      "Theatre Arts",
      "Yoruba",
    ],
  },
  {
    id: "unn",
    name: "University of Nigeria, Nsukka",
    departments: [
      "Accounting",
      "Agricultural Economics",
      "Agricultural Extension",
      "Animal Science",
      "Biochemistry",
      "Business Administration",
      "Chemistry",
      "Civil Engineering",
      "Computer Science",
      "Dentistry",
      "Economics",
      "Electrical and Electronic Engineering",
      "English",
      "Geology",
      "History and International Studies",
      "Law",
      "Library and Information Science",
      "Marketing",
      "Mathematics",
      "Mechanical Engineering",
      "Medicine and Surgery",
      "Microbiology",
      "Pharmacy",
      "Physiology",
      "Political Science",
      "Psychology",
      "Sociology",
      "Soil Science",
      "Statistics",
      "Veterinary Medicine",
    ],
  },
  {
    id: "abu",
    name: "Ahmadu Bello University, Zaria",
    departments: [
      "Accounting",
      "Actuarial Science",
      "Agricultural Engineering",
      "Agricultural Science & Education",
      "Agriculture",
      "Anatomy",
      "Arabic Studies",
      "Archaeology",
      "Architecture",
      "Banking & Finance",
      "Biochemistry",
      "Biological Sciences",
      "Botany",
      "Building",
      "Business Administration",
      "Business Education",
      "Chemical Engineering",
      "Chemistry",
      "Civil Engineering",
      "Computer Engineering",
      "Computer Science",
      "Dentistry & Dental Surgery",
      "Drama / Performing Arts",
      "Economics",
      "Education & Arabic",
      "Education & Biology",
      "Education & Chemistry",
      "Education & Geography",
      "Education & History",
      "Education & Mathematics",
      "Education & Physics",
      "Education & Social Studies",
      "Electrical & Computer Engineering",
      "English Language",
      "Fine Art",
      "Fisheries & Aquaculture",
      "Forestry & Wildlife Management",
      "French",
      "Geography",
      "Geology",
      "Glass Technology",
      "Guidance & Counselling",
      "Health Education",
      "History",
      "Home Economics & Education",
      "Human Kinetics",
      "Industrial Design",
      "Insurance",
      "International Studies",
      "Islamic / Sharia Law",
      "Library & Information Science",
      "Literature in English",
      "Local Government & Development Studies",
      "Marketing",
      "Mass Communication",
      "Mathematics",
      "Mechanical Engineering",
      "Medicine & Surgery",
      "Mechatronics Engineering",
      "Metallurgical Engineering",
      "Microbiology",
      "Mining Engineering",
      "Nursing Science",
      "Pharmacy",
      "Physics",
      "Physiology",
      "Political Science",
      "Public Administration",
      "Quantity Surveying",
      "Radiography",
      "Sociology",
      "Statistics",
      "Surveying & Geo‑Informatics",
      "Textile Science & Technology",
      "Theatre & Performing Arts",
      "Urology",
      "Urban & Regional Planning",
      "Veterinary Medicine",
      "Water Resources & Environmental Engineering",
      "Zoology",
    ],
  },
  {
    id: "unilorin",
    name: "University of Ilorin",
    departments: [
      "Agricultural Economics & Farm Management",
      "Agricultural Extension & Rural Development",
      "Agronomy",
      "Animal Production",
      "Aquaculture & Fisheries",
      "Crop Protection",
      "Home Economics & Food Science",
      "Soil Science",
      "Arabic",
      "Christian Religious Studies",
      "Comparative Religious Studies",
      "English",
      "French",
      "History & International Studies",
      "Islamic Studies",
      "Linguistics",
      "Performing & Film Arts",
      "Yoruba",
      "Anatomy",
      "Physiology",
      "Medical Biochemistry",
      "Computer Science",
      "Information & Communication Science",
      "Library & Information Science",
      "Mass Communication",
      "Telecommunication Science",
      "Adult & Primary Education",
      "Arts Education",
      "Counsellor Education",
      "Educational Management",
      "Educational Technology",
      "Environmental Health Education",
      "Human Kinetics Education",
      "Science Education",
      "Social Sciences Education",
      "Special Education",
      "Agricultural & Biosystems Engineering",
      "Biomedical Engineering",
      "Chemical Engineering",
      "Civil Engineering",
      "Computer Engineering",
      "Electrical Engineering",
      "Food & Bioprocess Engineering",
      "Materials & Metallurgical Engineering",
      "Mechanical Engineering",
      "Water Resources & Environmental Engineering",
      "Chemistry",
      "Geology & Mineral Science",
      "Industrial Chemistry",
      "Mathematics",
      "Physics",
      "Statistics",
      "Geography",
      "Political Science",
      "Psychology",
      "Social Work",
      "Sociology",
      "Veterinary Anatomy",
      "Veterinary Medicine",
      "Veterinary Microbiology",
      "Veterinary Parasitology & Entomology",
      "Veterinary Pathology",
      "Veterinary Pharmacology & Toxicology",
      "Veterinary Physiology & Biochemistry",
      "Veterinary Public Health & Preventive Medicine",
      "Veterinary Surgery & Radiology",
      "Veterinary Theriogenology & Production",
    ],
  },
  {
    id: "uniben",
    name: "University of Benin",
    departments: [
      "English & Literature",
      "Foreign Languages",
      "Fine & Applied Arts",
      "Linguistics & African Languages",
      "Philosophy & Religious Studies",
      "Theatre Arts & Mass Communication",
      "Animal Science",
      "Agricultural Economics & Extension",
      "Crop Science",
      "Fisheries",
      "Food Science",
      "Architecture",
      "Estate Management",
      "Geomatics (Surveying & Geoinformatics)",
      "Quantity Surveying",
      "Chemistry",
      "Computer Science",
      "Geology",
      "Mathematics",
      "Physics",
      "Statistics",
      "Accounting",
      "Actuarial Science",
      "Banking & Finance",
      "Business Administration",
      "Human Resource Management",
      "Insurance",
      "Marketing",
      "Electrical & Electronics Engineering",
      "Mechanical Engineering",
      "Petroleum Engineering",
      "Production Engineering",
    ],
  },
  {
    id: "futa",
    name: "Federal University of Technology, Akure",
    departments: [
      "Computer Science",
      "Software Engineering",
      "Civil Engineering",
      "Mechanical Engineering",
      "Electrical & Electronics Engineering",
      "Chemical Engineering",
      "Agricultural & Environmental Engineering",
      "Architecture",
      "Industrial Design",
      "Cybersecurity",
      "Project Management",
      "Information Technology",
      "Building Technology",
      "Estate Management",
      "Urban & Regional Planning",
    ],
  },
  {
    id: "unizik",
    name: "Nnamdi Azikiwe University, Awka",
    departments: [
      "Accounting & Finance",
      "Agricultural Economics",
      "Biochemistry",
      "Business Administration",
      "Chemical Engineering",
      "Civil Engineering",
      "Computer Science",
      "Economics",
      "Electrical & Electronics Engineering",
      "English Language & Literature",
      "Geography & Environmental Management",
      "History & International Studies",
      "Law",
      "Mechanical Engineering",
      "Mass Communication",
      "Mathematics",
      "Microbiology",
      "Pharmacy",
      "Physics",
      "Political Science",
      "Psychology",
      "Sociology",
      "Statistics",
      "Veterinary Medicine",
    ],
  },
  {
    id: "unijos",
    name: "University of Jos",
    departments: [
      "Accounting",
      "Adult Education",
      "Agricultural Economics",
      "Animal Science",
      "Architecture",
      "Banking & Finance",
      "Biochemistry",
      "Biology",
      "Business Administration",
      "Chemistry",
      "Civil Engineering",
      "Computer Science",
      "Economics",
      "Electrical & Electronics Engineering",
      "English & Literary Studies",
      "Estate Management",
      "Geology",
      "History & International Studies",
      "Law",
      "Library & Information Science",
      "Mathematics",
      "Mechanical Engineering",
      "Medicine & Surgery",
      "Microbiology",
      "Pharmacy",
      "Physics",
      "Political Science",
      "Psychology",
      "Public Administration",
      "Sociology",
      "Statistics",
      "Surveying & Geoinformatics",
      "Theatre & Performing Arts",
      "Urban & Regional Planning",
    ],
  },
  {
    id: "bayero",
    name: "Bayero University, Kano",
    departments: [
      "Accounting",
      "Agriculture",
      "Animal Science",
      "Architecture",
      "Biochemistry",
      "Biological Sciences",
      "Botany",
      "Business Administration",
      "Chemistry",
      "Civil Engineering",
      "Computer Science",
      "Economics",
      "Electrical Engineering",
      "English",
      "Environmental Management",
      "Geology",
      "History & International Studies",
      "Law",
      "Library & Information Science",
      "Mathematics",
      "Mechanical Engineering",
      "Medicine & Surgery",
      "Microbiology",
      "Nursing Science",
      "Pharmacy",
      "Physics",
      "Political Science",
      "Public Administration",
      "Sociology",
      "Statistics",
      "Veterinary Medicine",
    ],
  },
  {
    id: "unical",
    name: "University of Calabar",
    departments: [
      "Accounting",
      "Agricultural Science & Education",
      "Architecture",
      "Biochemistry",
      "Biological Sciences",
      "Botany",
      "Business Administration",
      "Chemistry",
      "Civil Engineering",
      "Computer Science",
      "Economics",
      "Electrical & Electronics Engineering",
      "English & Literary Studies",
      "Geography",
      "Geology",
      "History & International Studies",
      "Law",
      "Library & Information Science",
      "Mathematics",
      "Mechanical Engineering",
      "Medicine & Surgery",
      "Microbiology",
      "Pharmacy",
      "Physics",
      "Political Science",
      "Psychology",
      "Sociology",
      "Statistics",
      "Theatre Arts",
    ],
  },
  {
    id: "uniport",
    name: "University of Port Harcourt",
    departments: [
      "Accounting",
      "Agricultural Economics & Extension",
      "Agricultural Engineering",
      "Animal Science",
      "Architecture",
      "Banking & Finance",
      "Biochemistry",
      "Biology",
      "Business Administration",
      "Chemical Engineering",
      "Chemistry",
      "Civil Engineering",
      "Computer Science",
      "Economics",
      "Electrical & Electronics Engineering",
      "English & Literary Studies",
      "Geography",
      "Geology",
      "History & International Studies",
      "Law",
      "Library & Information Science",
      "Marine Biology",
      "Mathematics",
      "Mechanical Engineering",
      "Medicine & Surgery",
      "Microbiology",
      "Petroleum Engineering",
      "Pharmacy",
      "Physics",
      "Political Science",
      "Psychology",
      "Sociology",
      "Statistics",
      "Theatre Arts",
      "Urban & Regional Planning",
    ],
  },
  {
    id: "lasu",
    name: "Lagos State University (LASU)",
    departments: [
      "Accounting",
      "Adult & Primary Education",
      "Agricultural Science",
      "Biochemistry",
      "Business Administration",
      "Chemistry",
      "Civil Engineering",
      "Computer Science",
      "Economics",
      "Electrical/Electronics Engineering",
      "English",
      "Estate Management",
      "Fine & Applied Arts",
      "Geography",
      "History & International Studies",
      "Law",
      "Library & Information Science",
      "Mathematics",
      "Mechanical Engineering",
      "Medicine & Surgery",
      "Microbiology",
      "Pharmacy",
      "Physics",
      "Political Science",
      "Psychology",
      "Sociology",
      "Statistics",
      "Urban & Regional Planning",
    ],
  },
  {
    id: "panatl",
    name: "Pan-Atlantic University",
    departments: [
      "Accounting",
      "Business Administration",
      "Economics",
      "Finance",
      "Marketing",
      "Media & Communication",
      "Computer Science",
      "Information Technology",
      "Strategic Communication",
      "Film & Multimedia Studies",
    ],
  },
  {
    id: "babc",
    name: "Babcock University",
    departments: [
      "Accounting",
      "Biochemistry",
      "Biological Sciences",
      "Business Administration",
      "Computer Science",
      "Dentistry",
      "Economics",
      "Electrical/Electronics Engineering",
      "English & Literary Studies",
      "Industrial Chemistry",
      "Law",
      "Mass Communication",
      "Mathematics",
      "Mechanical Engineering",
      "Medicine & Surgery",
      "Microbiology",
      "Nursing Science",
      "Pharmacy",
      "Physiotherapy",
      "Political Science",
      "Psychology",
      "Sociology",
      "Theatre Arts",
      "Veterinary Medicine",
    ],
  },
  {
    id: "landmark",
    name: "Landmark University",
    departments: [
      "Accounting",
      "Agricultural Economics & Farm Management",
      "Agricultural Engineering",
      "Agronomy",
      "Animal Science",
      "Biochemistry",
      "Business Administration",
      "Chemical Engineering",
      "Civil Engineering",
      "Computer Science",
      "Economics",
      "Electrical & Electronics Engineering",
      "Food Science & Technology",
      "Industrial Chemistry",
      "Mechanical Engineering",
      "Software Engineering",
      "Mass Communication",
      "Mathematics",
    ],
  },
  {
    id: "abuad",
    name: "Afe Babalola University (ABUAD)",
    departments: [
      "Accounting",
      "Architecture",
      "Biochemistry",
      "Business Administration",
      "Civil Engineering",
      "Computer Science",
      "Economics",
      "Electrical & Electronics Engineering",
      "English & Literary Studies",
      "Law",
      "Mechanical Engineering",
      "Medicine & Surgery",
      "Pharmacy",
      "Political Science",
      "Software Engineering",
    ],
  },
  {
    id: "redeemer",
    name: "Redeemer's University",
    departments: [
      "Accounting",
      "Actuarial Science",
      "Biochemistry",
      "Biological Sciences",
      "Business Administration",
      "Chemical Engineering",
      "Civil Engineering",
      "Computer Science",
      "Economics",
      "Electrical/Electronics Engineering",
      "English & Literary Studies",
      "Entrepreneurship",
      "Finance",
      "Law",
      "Mass Communication",
      "Mechanical Engineering",
      "Microbiology",
      "Pharmacy",
      "Political Science",
      "Software Engineering",
      "Theatre Arts",
      "Zoology",
    ],
  },
  {
    id: "abuja",
    name: "University of Abuja",
    departments: [
      "Accounting",
      "Adult & Primary Education",
      "Agricultural Economics & Extension",
      "Agricultural Science",
      "Architecture",
      "Banking & Finance",
      "Biochemistry",
      "Biological Sciences",
      "Business Administration",
      "Chemical Engineering",
      "Chemistry",
      "Civil Engineering",
      "Computer Science",
      "Economics",
      "Electrical & Electronics Engineering",
      "English & Literary Studies",
      "Geography",
      "Geology",
      "History & International Studies",
      "Law",
      "Library & Information Science",
      "Mathematics",
      "Mechanical Engineering",
      "Medicine & Surgery",
      "Microbiology",
      "Pharmacy",
      "Physics",
      "Political Science",
      "Psychology",
      "Sociology",
      "Statistics",
      "Theatre & Performing Arts",
      "Urban & Regional Planning",
    ],
  },
  {
    id: "kwasu",
    name: "Kwara State University",
    departments: [
      "Accounting",
      "Agricultural Economics & Extension",
      "Agricultural Science & Education",
      "Animal Science",
      "Architecture",
      "Biochemistry",
      "Biological Sciences",
      "Business Administration",
      "Chemical Engineering",
      "Chemistry",
      "Civil Engineering",
      "Computer Science",
      "Economics",
      "Electrical & Electronics Engineering",
      "English",
      "Geography",
      "Geology",
      "History & International Studies",
      "Law",
      "Library & Information Science",
      "Mathematics",
      "Mechanical Engineering",
      "Medicine & Surgery",
      "Microbiology",
      "Nursing Science",
      "Pharmacy",
      "Physics",
      "Political Science",
      "Psychology",
      "Sociology",
      "Statistics",
    ],
  },
  {
    id: "unilori",
    name: "Adekunle Ajasin University (AAUA)",
    departments: [
      "Accounting",
      "Agricultural Economics & Extension",
      "Agricultural Science & Education",
      "Animal Science",
      "Architecture",
      "Biochemistry",
      "Biological Sciences",
      "Business Administration",
      "Chemical Engineering",
      "Chemistry",
      "Civil Engineering",
      "Computer Science",
      "Economics",
      "Electrical & Electronics Engineering",
      "English & Literary Studies",
      "Geography",
      "History & International Studies",
      "Law",
      "Library & Information Science",
      "Mathematics",
      "Mechanical Engineering",
      "Medicine & Surgery",
      "Microbiology",
      "Nursing Science",
      "Pharmacy",
      "Physics",
      "Political Science",
      "Psychology",
      "Sociology",
      "Statistics",
    ],
  },
  {
    id: "nile",
    name: "Nile University of Nigeria",
    departments: [
      "Accounting",
      "Actuarial Science",
      "Architecture",
      "Banking & Finance",
      "Biochemistry",
      "Biological Sciences",
      "Business Administration",
      "Chemical Engineering",
      "Civil Engineering",
      "Computer Science",
      "Economics",
      "Electrical & Electronics Engineering",
      "English & Literary Studies",
      "Law",
      "Mechanical Engineering",
      "Mass Communication",
      "Medicine & Surgery",
      "Pharmacy",
      "Political Science",
      "Software Engineering",
      "Statistics",
      "Zoology",
    ],
  },
  {
    id: "babcock2",
    name: "Bowen University",
    departments: [
      "Accounting",
      "Agricultural Economics",
      "Biochemistry",
      "Biological Sciences",
      "Business Administration",
      "Computer Science",
      "Economics",
      "Electrical/Electronics Engineering",
      "Law",
      "Mass Communication",
      "Mechanical Engineering",
      "Medicine & Surgery",
      "Microbiology",
      "Pharmacy",
      "Political Science",
      "Software Engineering",
      "Theatre Arts",
    ],
  },
  {
    id: "ekiti",
    name: "Ekiti State University",
    departments: [
      "Accounting",
      "Agricultural Science",
      "Animal Science",
      "Architecture",
      "Biochemistry",
      "Biological Sciences",
      "Business Administration",
      "Chemical Engineering",
      "Civil Engineering",
      "Computer Science",
      "Economics",
      "Electrical & Electronics Engineering",
      "English & Literary Studies",
      "Geography",
      "Geology",
      "History & International Studies",
      "Law",
      "Library & Information Science",
      "Mathematics",
      "Mechanical Engineering",
      "Medicine & Surgery",
      "Microbiology",
      "Nursing Science",
      "Pharmacy",
      "Physics",
      "Political Science",
      "Psychology",
      "Sociology",
      "Statistics",
      "Urban & Regional Planning",
    ],
  },
  {
    id: "futo",
    name: "Federal University of Technology, Owerri (FUTO)",
    departments: [
      "Agricultural Engineering",
      "Biochemistry",
      "Civil Engineering",
      "Computer Science",
      "Electrical & Electronics Engineering",
      "Food Science & Technology",
      "Mechanical Engineering",
      "Metallurgical & Materials Engineering",
      "Petroleum Engineering",
      "Polymer & Textile Engineering",
      "Chemical Engineering",
      "Project Management",
      "Software Engineering",
      "Statistics",
    ],
  },
  {
    id: "aun",
    name: "American University of Nigeria (AUN)",
    departments: [
      "Accounting",
      "Business Administration",
      "Computer Science",
      "Economics",
      "Electrical & Electronics Engineering",
      "International Relations",
      "Mechanical Engineering",
      "Political Science",
      "Software Engineering",
      "Mass Communication",
      "Psychology",
    ],
  },
  {
    id: "uniuyo",
    name: "University of Uyo",
    departments: [
      "Accounting",
      "Adult Education",
      "Agricultural Economics",
      "Animal Science",
      "Architecture",
      "Banking & Finance",
      "Biochemistry",
      "Biology",
      "Business Administration",
      "Chemical Engineering",
      "Chemistry",
      "Civil Engineering",
      "Computer Science",
      "Economics",
      "Electrical & Electronics Engineering",
      "English & Literary Studies",
      "Geography",
      "Geology",
      "History & International Studies",
      "Law",
      "Library & Information Science",
      "Mathematics",
      "Mechanical Engineering",
      "Medicine & Surgery",
      "Microbiology",
      "Pharmacy",
      "Physics",
      "Political Science",
      "Psychology",
      "Sociology",
      "Statistics",
      "Urban & Regional Planning",
    ],
  },
  {
    id: "auw",
    name: "American University of West Africa",
    departments: [
      "Accounting",
      "Business Administration",
      "Computer Science",
      "Economics",
      "Electrical & Electronics Engineering",
      "Mass Communication",
      "Mechanical Engineering",
      "Political Science",
      "Software Engineering",
      "International Relations",
      "Psychology",
    ],
  },
];

// Helper function to get departments for a specific school
export const getDepartmentsBySchoolId = (schoolId: string): string[] => {
  const school = SCHOOLS.find((s) => s.id === schoolId);
  return school ? school.departments : [];
};

// Helper function to get school by ID
export const getSchoolById = (schoolId: string): School | undefined => {
  return SCHOOLS.find((s) => s.id === schoolId);
};
