export interface School {
  id: string;
  name: string;
  departments: string[];
}

export const SCHOOLS: School[] = [
  {
    id: "ui",
    name: "University of Ibadan",
    departments: [
      "Computer Science",
      "Medicine",
      "Law",
      "Economics",
      "Psychology",
      "Mass Communication",
      "Architecture",
      "Fine Arts",
      "Civil Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Chemical Engineering",
      "Pharmacy",
      "Nursing",
      "Veterinary Medicine",
    ],
  },
  {
    id: "unilag",
    name: "University of Lagos",
    departments: [
      "Computer Science",
      "Medicine",
      "Law",
      "Business Administration",
      "Economics",
      "Mass Communication",
      "Architecture",
      "Engineering",
      "Pharmacy",
      "Creative Arts",
      "Education",
      "Social Work",
    ],
  },
  {
    id: "oau",
    name: "Obafemi Awolowo University",
    departments: [
      "Computer Science",
      "Medicine",
      "Law",
      "Economics",
      "Psychology",
      "Mass Communication",
      "Fine Arts",
      "Civil Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Agricultural Engineering",
      "Pharmacy",
      "Dentistry",
    ],
  },
  {
    id: "abu",
    name: "Ahmadu Bello University",
    departments: [
      "Computer Science",
      "Medicine",
      "Law",
      "Economics",
      "Business Administration",
      "Architecture",
      "Civil Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Agricultural Engineering",
      "Pharmacy",
      "Veterinary Medicine",
    ],
  },
  {
    id: "unn",
    name: "University of Nigeria, Nsukka",
    departments: [
      "Computer Science",
      "Medicine",
      "Law",
      "Economics",
      "Psychology",
      "Mass Communication",
      "Fine Arts",
      "Engineering",
      "Pharmacy",
      "Education",
      "Environmental Science",
    ],
  },
  {
    id: "covenant",
    name: "Covenant University",
    departments: [
      "Computer Science",
      "Software Engineering",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering",
      "Chemical Engineering",
      "Business Administration",
      "Economics",
      "Mass Communication",
      "Architecture",
      "Biochemistry",
      "Industrial Chemistry",
    ],
  },
  {
    id: "babcock",
    name: "Babcock University",
    departments: [
      "Computer Science",
      "Medicine",
      "Law",
      "Nursing",
      "Business Administration",
      "Mass Communication",
      "Architecture",
      "Engineering",
      "Pharmacy",
      "Public Health",
      "Education",
    ],
  },
  {
    id: "futa",
    name: "Federal University of Technology, Akure",
    departments: [
      "Computer Science",
      "Software Engineering",
      "Civil Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Chemical Engineering",
      "Agricultural Engineering",
      "Architecture",
      "Industrial Design",
      "Cybersecurity",
      "Project Management",
    ],
  },
  {
    id: "lasu",
    name: "Lagos State University",
    departments: [
      "Computer Science",
      "Medicine",
      "Law",
      "Business Administration",
      "Economics",
      "Mass Communication",
      "Fine Arts",
      "Engineering",
      "Education",
      "Sociology",
    ],
  },
  {
    id: "landmark",
    name: "Landmark University",
    departments: [
      "Computer Science",
      "Software Engineering",
      "Civil Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Agricultural Engineering",
      "Business Administration",
      "Economics",
      "Mass Communication",
      "Biochemistry",
    ],
  },
  {
    id: "unilorin",
    name: "University of Ilorin",
    departments: [
      "Computer Science",
      "Medicine",
      "Law",
      "Economics",
      "Business Administration",
      "Mass Communication",
      "Engineering",
      "Pharmacy",
      "Education",
      "Performing Arts",
    ],
  },
  {
    id: "pau",
    name: "Pan-Atlantic University",
    departments: [
      "Computer Science",
      "Business Administration",
      "Economics",
      "Mass Communication",
      "Media & Communication",
      "Finance",
      "Marketing",
      "Accounting",
      "Management",
    ],
  },
];

// Helper function to get departments for a specific school
export const getDepartmentsBySchoolId = (schoolId: string): string[] => {
  const school = SCHOOLS.find((s) => s.id === schoolId);
  return school ? school.departments : [];
};

// Helper function to get school by ID
export const getSchoolById = (schoolId: string): School | undefined => {
  return SCHOOLS.find((s) => s.id === schoolId);
};
